spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        use_sql_comments: true

  datasource:
    username: postgres
    password: 1111
    url: jdbc:postgresql://localhost:5432/carrot
    driver-class-name: org.postgresql.Driver

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
